### ISSUE TITLE
Error: Failed to sign request: Request failed with status code 429

### ISSUE THREAD

**Issue by acaksandi** [zerodytrash/TikTok-Chat-Reader#14]
I got this error
"Error: Failed to sign request: Request failed with status code 429"
what should I do?

**Comment by zerodytrash** [comment]
you can only have two simultaneous connections to tiktok and send a maximum of 4 connection requests per minute. 
have you reached this limit?

Status Code 429 = Too Many Requests

**Comment by RuckieOfficial** [comment]
@zerodytrash Is it still maintained? Because it is not working even on the demo :/
https://tiktok-chat-reader.zerody.one/

You can connect, but dont see any messages or gifts.

**Comment by vioan** [comment]
is not working since two weeks, and it seems that is not fixed yet

**Comment by zerodytrash** [comment]
> Is it still maintained? Because it is not working even on the demo :/

@RuckieOfficial Have just fixed the demo. At the moment it runs without errors. The server IP was probably blocked by TikTok.

If you host it yourself (locally or on your own server) then it should currently work as well. The only restriction is that you can only make up to three connection requests per minute. Also make sure you have the latest version and all packages are up to date. Let me know if there are still problems.

**Comment by vioan** [comment]
it seems that again is not working, I am getting:

`Error: Failed to sign request: Request failed with status code 500; URL: https://webcast.tiktok.com/webcast/im/fetch/ .....`

**Comment by zerodytrash** [comment]
fixed
