### ISSUE TITLE
Error: Failed to retrieve room_id from page source. Your IP or country might be blocked by TikTok.

### ISSUE THREAD

**Issue by dragosite** [zerodytrash/TikTok-Chat-Reader#40]
I am getting this error locally, using the python version as well as the example website (https://tiktok-chat-reader.zerody.one)?

**Comment by zerodytrash** [comment]
This issue is now fixed. https://github.com/zerodytrash/TikTok-Chat-Reader/commit/959f05d17b8a649247fc186ca9c4c2ebaeba43b8

**Comment by dragosite** [comment]
Hi @zerodytrash 

Thanks for you quick reply, now works! Looking at your bounty payouts you probably don't need it :) but let me know where I can buy you a coffee for this repo.

Thanks,
Dragos

**Comment by zerodytrash** [comment]
You can find the donation links in the sponsor section of the library repo https://github.com/zerodytrash/TikTok-Live-Connector
Thanks!
