### ISSUE TITLE
Installing script on cPanel

### ISSUE THREAD

**Issue by kasperzi** [zerodytrash/TikTok-Chat-Reader#6]
Hello,

I have an issue when trying to install this script on cPanel, even with the setup Node.js application.
Contacted you on Keybase/Twitter.

**Comment by arcizy** [comment]
Yeah i have the same issue. Do we have to install live connector module first?
Please make some tutorial

**Comment by zerodytrash** [comment]
I dont use cPanel. Generally you need a server on that you can run Node. For example a Linux VPS. This is also possible using the console.

Here is a documentation describing how to set up Node applications with cPanel:
https://docs.cpanel.net/knowledge-base/web-services/how-to-install-a-node.js-application/

If I read this correctly, the Node.js support is only experimental in cPanel. Therefore, it might make more sense to connect to the server via SSH and install Node yourself.

**Comment by kasperzi** [comment]
For sure, tested on Linux and everything worked. Another reason for me just to stop using the cPanel :D
